### ISSUE TITLE
Ordering alert threshold sometimes raise "Unexpected Error"

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#178] opened 2018-01-04 09:44 UTC
When user click on up/down arrow to order alert threshold sometimes, raise "Unexpected Error", and sometimes nothing happens

**Comment by Thyda-Eng** [comment] 2018-01-10 03:17
It is fixed with #179 , I cannot reproduce it anymore.

**Closed as completed** 2018-01-11 01:52 UTC
Labels: bug, critical
