### ISSUE TITLE
Unexpected Error when create site that reached alert with date criteria and email

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#180] opened 2018-01-05 08:42 UTC
As a collection owner
When I create an alert threshold with 
   1. date field less than 1/1/2018
   2. email field equal 'test@abc.com'
Then user can't submit offline site that reached this alert
And there is nothing happen to let user know on the submission window

**Comment by Thyda-Eng** [comment] 2018-01-10 03:16
It is fixed with #179 , I cannot reproduce it anymore.

**Closed as completed** 2018-01-11 01:52 UTC
Labels: bug
